-- SPDX-FileCopyrightText: 2025 Google LLC
--
-- SPDX-License-Identifier: Apache-2.0
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE RankNTypes #-}

module Bittide.Cpus.Riscv32imc (vexRiscv) where

-- Note: We could re-export `vexRiscv` directly, but I thought it would be nice
-- to have a source that shows the type signature instead of it being tucked
-- away in an autogenerated module.
import Clash.Prelude

import VexRiscv (CpuIn, CpuOut, DumpVcd, JtagIn, JtagOut)
import VexRiscv.Reset (MinCyclesReset)

import qualified VexRiscv_Riscv32imc

vexRiscv ::
  forall dom.
  (KnownDomain dom) =>
  DumpVcd ->
  Clock dom ->
  MinCyclesReset dom 2 ->
  Signal dom CpuIn ->
  Signal dom JtagIn ->
  ( Signal dom CpuOut
  , Signal dom JtagOut
  )
vexRiscv = VexRiscv_Riscv32imc.vexRiscv
