# SPDX-FileCopyrightText: 2022 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "bittide-sys"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Google LLC"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
fdt = "0.1.0"
log = "0.4.21"
ufmt = "0.2.0"
bittide-hal = { path = "../bittide-hal" }
itertools = { version = "0.14.0", default-features = false }

[dependencies.heapless]
version = "0.8"
features = ["ufmt"]

[dependencies.rand]
version = "0.8.3"
features = ["small_rng"]
default-features = false

[dependencies.smoltcp]
version = "0.12.0"
default-features = false
features = ["log", "medium-ethernet", "proto-ipv4", "socket-tcp"]

[dev-dependencies]
proptest = "1.0"
object = { version = "0.28", features = ["write"] }
libc = "0.2"
test-strategy = "0.2.0"
rand = "0.8"
lazy_static = "1.0"
tempfile = "3"
