MEMORY
{
  INSTR : ORIGIN = 0x10000000, LENGTH = 128K
  DATA  : ORIGIN = 0x60000000, LENGTH = 128K
}

REGION_ALIAS("REGION_TEXT", INSTR);
REGION_ALIAS("REGION_RODATA", DATA);
REGION_ALIAS("REGION_DATA", DATA);
REGION_ALIAS("REGION_BSS", DATA);
REGION_ALIAS("REGION_HEAP", DATA);
REGION_ALIAS("REGION_STACK", DATA);
