# SPDX-FileCopyrightText: 2022 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[build]
target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["core,panic_abort"]
build-std-features = ["panic_immediate_abort"]
