# SPDX-FileCopyrightText: 2022 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "clock-control-wb"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Google LLC"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bittide-sys = { path = "../../../firmware-support/bittide-sys" }
bittide-hal = { path = "../../../firmware-support/bittide-hal" }
rand = {version = "0.8.3", features = ["small_rng"], default-features = false }
riscv-rt = "0.11.0"
ufmt = "0.2.0"

[build-dependencies]
memmap-generate = { path = "../../../firmware-support/memmap-generate" }
