# SPDX-FileCopyrightText: 2022 Google LLC
#
# SPDX-License-Identifier: Apache-2.0

# create_clock -name {SYSCLK_300_P} -period 3.333 -waveform {0.000 1.667} [get_ports {SYSCLK_300_P}]
create_clock -period 5.000 -name USER_SMA_CLOCK_P -waveform {0.000 2.500} [get_ports USER_SMA_CLOCK_P]
create_clock -period 5.000 -name FMC_HPC_CLK1_M2C_P -waveform {0.000 2.500} [get_ports FMC_HPC_CLK1_M2C_P]
create_clock -period 5.000 -name FMC_LPC_CLK1_M2C_P -waveform {0.000 2.500} [get_ports FMC_LPC_CLK1_M2C_P]

#set_property IOSTANDARD DIFF_SSTL12 [get_ports SYSCLK_300_P]
#set_property ODT RTT_48 [get_ports SYSCLK_300_P]
#
# Bank  45 VCCO - VCC1V2_FPGA_3A - IO_L12N_T1U_N11_GC_45
#set_property PACKAGE_PIN AK17 [get_ports SYSCLK_300_P]
#set_property PACKAGE_PIN AK16 [get_ports SYSCLK_300_N]
#set_property IOSTANDARD DIFF_SSTL12 [get_ports SYSCLK_300_N]
#set_property ODT RTT_48 [get_ports SYSCLK_300_N]

# Bank  67 VCCO - VADJ_1V8_FPGA_10A - IO_L13P_T2L_N0_GC_QBC_67
set_property IOSTANDARD LVDS [get_ports USER_SMA_CLOCK_P]
set_property DIFF_TERM_ADV TERM_100 [get_ports USER_SMA_CLOCK_P]
#
# Bank  67 VCCO - VADJ_1V8_FPGA_10A - IO_L13N_T2L_N1_GC_QBC_67
set_property PACKAGE_PIN D23 [get_ports USER_SMA_CLOCK_P]
set_property PACKAGE_PIN C23 [get_ports USER_SMA_CLOCK_N]
set_property IOSTANDARD LVDS [get_ports USER_SMA_CLOCK_N]
set_property DIFF_TERM_ADV TERM_100 [get_ports USER_SMA_CLOCK_N]

# Bank  67 VCCO - VADJ_1V8_FPGA_10A - IO_L11P_T1U_N8_GC_67
set_property IOSTANDARD LVDS [get_ports FMC_HPC_CLK1_M2C_P]
set_property DIFF_TERM_ADV TERM_100 [get_ports FMC_HPC_CLK1_M2C_P]
#
# Bank  67 VCCO - VADJ_1V8_FPGA_10A - IO_L11N_T1U_N9_GC_67
set_property PACKAGE_PIN E25 [get_ports FMC_HPC_CLK1_M2C_P]
set_property PACKAGE_PIN D25 [get_ports FMC_HPC_CLK1_M2C_N]
set_property IOSTANDARD LVDS [get_ports FMC_HPC_CLK1_M2C_N]
set_property DIFF_TERM_ADV TERM_100 [get_ports FMC_HPC_CLK1_M2C_N]

# Bank  48 VCCO - VADJ_1V8_FPGA_10A - IO_L12P_T1U_N10_GC_48
set_property IOSTANDARD LVDS [get_ports FMC_LPC_CLK1_M2C_P]
set_property DIFF_TERM_ADV TERM_100 [get_ports FMC_LPC_CLK1_M2C_P]
#
# Bank  48 VCCO - VADJ_1V8_FPGA_10A - IO_L12N_T1U_N11_GC_48
set_property PACKAGE_PIN AC31 [get_ports FMC_LPC_CLK1_M2C_P]
set_property PACKAGE_PIN AC32 [get_ports FMC_LPC_CLK1_M2C_N]
set_property IOSTANDARD LVDS [get_ports FMC_LPC_CLK1_M2C_N]
set_property DIFF_TERM_ADV TERM_100 [get_ports FMC_LPC_CLK1_M2C_N]


set_clock_groups -asynchronous -group USER_SMA_CLOCK_P -group FMC_HPC_CLK1_M2C_P -group FMC_LPC_CLK1_M2C_P

# GPIO_SW_E
set_property PACKAGE_PIN AE8 [get_ports rstA]
set_property IOSTANDARD LVCMOS18 [get_ports rstA]

# CPIO_SW_C
set_property PACKAGE_PIN AE10 [get_ports rstB]
set_property IOSTANDARD LVCMOS18 [get_ports rstB]

# GPIO_SW_W
set_property PACKAGE_PIN AF9 [get_ports rstC]
set_property IOSTANDARD LVCMOS18 [get_ports rstC]

#clkC
set_property PACKAGE_PIN AP16 [get_ports domC_FDEC]
set_property IOSTANDARD LVCMOS12 [get_ports domC_FDEC]

set_property PACKAGE_PIN AN18 [get_ports domC_FINC]
set_property IOSTANDARD LVCMOS12 [get_ports domC_FINC]

#clkA
set_property PACKAGE_PIN AL14 [get_ports domA_FDEC]
set_property IOSTANDARD LVCMOS12 [get_ports domA_FDEC]

set_property PACKAGE_PIN AM16 [get_ports domA_FINC]
set_property IOSTANDARD LVCMOS12 [get_ports domA_FINC]

#clkB
set_property PACKAGE_PIN AM14 [get_ports domB_FDEC]
set_property IOSTANDARD LVCMOS12 [get_ports domB_FDEC]

set_property PACKAGE_PIN AM15 [get_ports domB_FINC]
set_property IOSTANDARD LVCMOS12 [get_ports domB_FINC]

#GPIO_LED_0_LS
set_property PACKAGE_PIN AP8 [get_ports domA_StableB]
set_property IOSTANDARD LVCMOS18 [get_ports domA_StableB]

#GPIO_LED_1_LS
set_property PACKAGE_PIN H23 [get_ports domA_StableC]
set_property IOSTANDARD LVCMOS18 [get_ports domA_StableC]

#GPIO_LED_2_LS
set_property PACKAGE_PIN P20 [get_ports domB_StableA]
set_property IOSTANDARD LVCMOS18 [get_ports domB_StableA]

# Bank  85 VCCO -          - IO_L20N_T3L_N3_AD1N_D09_65
set_property PACKAGE_PIN P21 [get_ports domB_StableC]
set_property IOSTANDARD LVCMOS18 [get_ports domB_StableC]

# Bank  85 VCCO -          - IO_L19P_T3L_N0_DBC_AD9P_D10_65
set_property PACKAGE_PIN N22 [get_ports domC_StableA]
set_property IOSTANDARD LVCMOS18 [get_ports domC_StableA]

# Bank  85 VCCO -          - IO_L19N_T3L_N1_DBC_AD9N_D11_65
set_property PACKAGE_PIN M22 [get_ports domC_StableB]
set_property IOSTANDARD LVCMOS18 [get_ports domC_StableB]

# Bank  85 VCCO -          - IO_L18P_T2U_N10_AD2P_D12_65
#GPIO_LED_6_LS
#set_property PACKAGE_PIN R23 [get_ports {EbMode[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {EbMode[0]}]
# Bank  85 VCCO -          - IO_L18N_T2U_N11_AD2N_D13_65
#GPIO_LED_7_LS
#set_property PACKAGE_PIN P23 [get_ports {EbMode[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {EbMode[1]}]


set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[3]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[0]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[15]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[13]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[14]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[11]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[12]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[1]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[2]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[4]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[5]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[6]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[7]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[8]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[9]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_4[10]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[3]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[0]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[15]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[13]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[14]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[1]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[2]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[4]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[5]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[6]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[7]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[8]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[9]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[10]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[11]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_2[12]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[3]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[0]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[15]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[1]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[2]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[4]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[5]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[6]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[7]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[8]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[9]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[10]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[11]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[12]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[13]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds1_0[14]}]


set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[15]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[0]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[1]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[11]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[10]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[14]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/result[6]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/ds[0]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/result[12]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/result[7]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/result[6]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/result[12]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/result[7]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/result[5]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/result[10]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/result[11]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[8]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[5]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[3]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[13]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[7]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[4]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[12]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[0]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[13]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[2]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[9]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[12]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/ds[0]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/result[7]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/result[4]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/result[11]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/result[5]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/result[4]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/result[3]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/result[13]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/result[15]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/result[9]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/result[12]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/result[14]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/result[6]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[2]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[12]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[4]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[3]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[9]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[11]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[8]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[7]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[14]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[3]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[4]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[6]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[7]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[15]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/result[10]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/result[9]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/result[13]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/result[8]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/result[14]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/result[14]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/ds[0]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/result[3]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/result[4]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[1]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[15]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[6]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[9]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[11]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[5]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[13]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_7[8]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/result[3]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/result[8]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/result[5]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/result[15]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/result[10]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/result[9]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/result[15]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/result[11]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/result[13]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/result[8]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[14]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[0]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[1]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[2]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[5]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_4[10]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[6]}]
set_property MARK_DEBUG false [get_nets {clockControlDemo2/ds_1[10]}]

set_property MARK_DEBUG true [get_nets domC_FDEC_OBUF]
set_property MARK_DEBUG true [get_nets domC_FINC_OBUF]
set_property MARK_DEBUG true [get_nets domA_StableB_OBUF]
set_property MARK_DEBUG true [get_nets domA_StableC_OBUF]
set_property MARK_DEBUG true [get_nets domB_StableA_OBUF]
set_property MARK_DEBUG true [get_nets domB_StableC_OBUF]
set_property MARK_DEBUG true [get_nets domC_StableA_OBUF]
set_property MARK_DEBUG true [get_nets domC_StableB_OBUF]
set_property MARK_DEBUG true [get_nets domB_FINC_OBUF]
set_property MARK_DEBUG true [get_nets domB_FDEC_OBUF]
set_property MARK_DEBUG true [get_nets domA_FDEC_OBUF]
set_property MARK_DEBUG true [get_nets domA_FINC_OBUF]
set_property MARK_DEBUG true [get_nets rstA_IBUF]
set_property MARK_DEBUG true [get_nets rstB_IBUF]
set_property MARK_DEBUG true [get_nets rstC_IBUF]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[10]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[13]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[12]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[11]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[9]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[8]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[7]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[6]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[5]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[4]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[2]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[3]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[13]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[15]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[14]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[12]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[11]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[10]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[9]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[8]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[7]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[6]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[4]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[5]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[10]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[13]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[12]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[11]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[9]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[8]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[7]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[6]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[5]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[4]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[3]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[2]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[11]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[13]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[12]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[10]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[9]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[8]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[7]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[6]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[5]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[4]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[3]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[2]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[11]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[15]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[14]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[13]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[12]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[10]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[9]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[8]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[7]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[6]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[5]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[4]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[11]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[15]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[14]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[13]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[12]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[10]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[9]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[8]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[7]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[6]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[5]}]
set_property MARK_DEBUG true [get_nets {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[4]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_2/inst/clkC]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 13 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[3]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[4]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[5]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[6]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[7]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[8]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[9]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[10]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[11]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[12]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[13]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[14]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/result[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/ds[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 12 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[2]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[3]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[4]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[5]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[6]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[7]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[8]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[9]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[10]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[11]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[12]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_0_ds1_0/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_0_ds/result[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/ds[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list domC_FDEC_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list domC_FINC_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list domC_StableA_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list domC_StableB_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list rstC_IBUF]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_wiz_1/inst/clkB]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_ds_1/ds[0]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 13 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[3]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[4]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[5]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[6]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[7]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[8]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[9]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[10]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[11]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[12]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[13]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[14]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_1_ds_4/result[15]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 12 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[2]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[3]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[4]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[5]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[6]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[7]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[8]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[9]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[10]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[11]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[12]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_2_ds1_2/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_2_ds/result[13]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list domB_FDEC_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list domB_FINC_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list domB_StableA_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list domB_StableC_OBUF]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list rstB_IBUF]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list clk_wiz_0/inst/clkA]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 13 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[3]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[4]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[5]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[6]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[7]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[8]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[9]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[10]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[11]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[12]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[13]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[14]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_3_ds_7/result[15]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 12 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[2]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[3]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[4]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[5]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[6]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[7]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[8]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[9]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[10]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[11]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[12]} {clockControlDemo2/Bittide_Instances_MVPs_clockControlDemo2_controlledFifo_4_ds1_4/Bittide_Instances_MVPs_clockControlDemo2_xilinxElasticBuffer_4_ds/result[13]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 1 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list domA_FDEC_OBUF]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 1 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list domA_FINC_OBUF]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property port_width 1 [get_debug_ports u_ila_2/probe4]
connect_debug_port u_ila_2/probe4 [get_nets [list domA_StableB_OBUF]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
set_property port_width 1 [get_debug_ports u_ila_2/probe5]
connect_debug_port u_ila_2/probe5 [get_nets [list domA_StableC_OBUF]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe6]
set_property port_width 1 [get_debug_ports u_ila_2/probe6]
connect_debug_port u_ila_2/probe6 [get_nets [list rstA_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clkA]
