# SPDX-FileCopyrightText: 2024 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "smoltcp_client"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Google LLC"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ufmt = "0.2.0"

[dependencies.bittide-sys]
path = "../../../firmware-support/bittide-sys"

[dependencies.gdb-trace]
path = "../../../firmware-support/gdb-trace"

[dependencies.heapless]
version = "0.8"
default-features = false

[dependencies.log]
version = "0.4.21"
features = ["max_level_off", "release_max_level_info"]

[dependencies.riscv]
git = "https://github.com/rslawson/riscv"
branch = "rs/lto-fixes"
package = "riscv"

[dependencies.riscv-rt]
git = "https://github.com/rslawson/riscv"
branch = "rs/lto-fixes"
package = "riscv-rt"

[dependencies.smoltcp]
git = "https://github.com/smoltcp-rs/smoltcp.git"
rev = "dc08e0b42e668c331bb2b6f8d80016301d0efe03"
default-features = false
features = ["medium-ethernet", "proto-ipv4", "socket-tcp", "socket-dhcpv4"]
