# SPDX-FileCopyrightText: 2024 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "time_self_test"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Google LLC"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bittide-sys = { path = "../../../firmware-support/bittide-sys" }
ufmt = "0.2.0"

[dependencies.riscv-rt]
git = "https://github.com/rslawson/riscv"
branch = "rs/lto-fixes"
package = "riscv-rt"
