# SPDX-FileCopyrightText: 2022 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "smoltcp-example"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Google LLC"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv-rt = "0.11.0"
riscv = "^0.10"
heapless = { version = "0.7", default-features = false}
smoltcp = { version = "0.9.1", default-features = false, features = ["log", "medium-ethernet", "proto-ipv4", "socket-tcp"] }
bittide-sys = { path = "../../bittide-sys" }
