/*
SPDX-FileCopyrightText: 2022 Google LLC

SPDX-License-Identifier: CC0-1.0
*/

MEMORY
{
  IMEM : ORIGIN = {imem_start}, LENGTH = {imem_size}
  DMEM : ORIGIN = {dmem_start}, LENGTH = {dmem_size}
}

REGION_ALIAS("REGION_TEXT", IMEM);
REGION_ALIAS("REGION_RODATA", DMEM);
REGION_ALIAS("REGION_DATA", DMEM);
REGION_ALIAS("REGION_BSS", DMEM);
REGION_ALIAS("REGION_HEAP", DMEM);
REGION_ALIAS("REGION_STACK", DMEM);
