# SPDX-FileCopyrightText: 2023 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "callisto-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bittide-sys = { path = "../../firmware-support/bittide-sys", default-features = false, features = []}

[lib]
crate-type = ["staticlib"]
