# SPDX-FileCopyrightText: 2022-2023 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[toolchain]
channel = "1.67.1"
targets = [ "riscv32imc-unknown-none-elf", "x86_64-unknown-linux-gnu" ]
profile = "minimal"
components = [ "clippy", "rustfmt" ]
