/*
SPDX-FileCopyrightText: 2022 Google LLC

SPDX-License-Identifier: CC0-1.0
*/

MEMORY
{
  RAM : ORIGIN = 0x80000000, LENGTH = 256K
}

REGION_ALIAS("REGION_TEXT", RAM);
REGION_ALIAS("REGION_RODATA", RAM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
