-- SPDX-FileCopyrightText: 2022 Google LLC
--
-- SPDX-License-Identifier: Apache-2.0
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE NamedFieldPuns #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE ViewPatterns #-}

{- | Helper functions to do things like synthesis, place & route, bitstream
generation, programming and running hardware tests for the Bittide project.
This is realized by letting Vivado execute Tcl using the `vivado-hs` package.
Refer to @bittide-instances/src/Bittide/Instances/Hitl/README.md@ and
`Bittide.Hitl` for more information on the HITL test infrastructure.
-}
module Clash.Shake.Vivado (
  LocatedManifest (..),
  BoardPart (..),
  TclGlobPattern,
  decodeLocatedManifest,
  decodeLocatedManifestNoNeed,
  runSynthesis,
  runPlaceAndRoute,
  runBitstreamGen,
  runProbesFileGen,
  deviceInfoFromHwTRef,
  programBitstream,
  runHitlTest,
  meetsTiming,
  meetsDrc,
) where

import Prelude

import Development.Shake (Action)
import Development.Shake.Extra (decodeFile)

import Bittide.Hitl
import Bittide.Instances.Hitl.Utils.Vivado
import Clash.Driver.Manifest
import Clash.Prelude (BitPack (BitSize), Natural, natToNatural, pack)
import Clash.Shake.Extra (hexDigestFile)
import Control.Concurrent.Async (mapConcurrently)
import Control.Exception (Exception (displayException), SomeException, catch, throwIO, try)
import Control.Monad.Extra (andM, forM, forM_, orM, unless, when)
import Control.Monad.Reader (runReaderT)
import Data.Containers.ListUtils (nubOrd)
import Data.List (isInfixOf, (\\))
import Data.List.Extra (anySame)
import Data.Maybe (fromJust)
import Data.String.Interpolate (__i)
import Data.Text (unpack)
import GHC.Stack (HasCallStack)
import System.Directory (createDirectoryIfMissing)
import System.Exit (ExitCode (..))
import System.FilePath (dropFileName, (</>))
import System.Process (readProcessWithExitCode)
import Vivado (TclException (..), VivadoHandle, execPrint_, with)
import Vivado.Tcl
import Vivado.VivadoM

import qualified Clash.Sized.Internal.BitVector as BitVector
import qualified Data.Aeson as Aeson
import qualified Data.Map.Strict as Map

-- | Satisfied if all actions result in 'False'
noneM :: (Monad m) => [m Bool] -> m Bool
noneM = fmap not . orM

-- | Whether a string occurs in a file
inFile :: String -> FilePath -> IO Bool
inFile msg path = do
  content <- readFile path
  pure $ (msg `isInfixOf` content)

{- | Read a timing summary or DRC report and determine whether it passed DRC
checks.
-}
meetsDrc :: FilePath -> IO Bool
meetsDrc path =
  noneM
    [ inFile "No report available as report_methodology has not been run prior." path
    , inFile "Critical Warning" path
    ]

-- | Read a timing summary and determine whether it met timing.
meetsTiming :: FilePath -> IO Bool
meetsTiming path =
  andM
    [ meetsDrc path -- for safety; users should use meetsDrc for useful error reporting
    , not <$> inFile "Timing constraints are not met" path
    ]

-- | Patterns compatible with https://www.tcl.tk/man/tcl8.6/TclCmd/glob.htm
type TclGlobPattern = String

-- TODO: Upstream
data LocatedManifest = LocatedManifest
  { lmPath :: FilePath
  -- ^ Path pointing to the manifest file itself
  , lmManifest :: Manifest
  -- ^ Manifest file corresponding to the one at 'lmPath'
  }

decodeLocatedManifest :: (HasCallStack) => FilePath -> Action LocatedManifest
decodeLocatedManifest path = LocatedManifest path <$> decodeFile path

decodeLocatedManifestNoNeed :: (HasCallStack) => FilePath -> IO LocatedManifest
decodeLocatedManifestNoNeed path =
  LocatedManifest path . fromJust <$> Aeson.decodeFileStrict path

{- | Vivado board part or part. If a board part is set, Vivado will infer the
part on that board.
-}
data BoardPart
  = Board String
  | Part String

-- | Generate Tcl that sets the board part or part for the current project
mkBoardPartTcl :: BoardPart -> String
mkBoardPartTcl boardPart = case boardPart of
  (Board name) -> "set_property board_part " <> name <> " [current_project]"
  (Part name) -> "set_property part " <> name <> " [current_project]"

{- | Generates TCL that generates and reads Xilinx IP and reads constraints and
HDL files generated by Clash. The caller is responsible for starting synthesis
or simulation.
-}
execBaseTcl ::
  -- | Handle to a Vivado object that is to execute the Tcl.
  VivadoHandle ->
  -- | Where to create ip directory.
  FilePath ->
  -- | List of glob patterns to external HDL files.
  [TclGlobPattern] ->
  -- | Top entity directory
  LocatedManifest ->
  -- | Board part or part to synthesize for
  BoardPart ->
  {- | Path to tclConnector: a Tcl script that can parse Clash output and emit
  the correct commands for loading the design into Vivado
  -}
  FilePath ->
  IO ()
execBaseTcl v outputDir globPatterns LocatedManifest{lmPath} boardPart connector = do
  connectorDigest <- hexDigestFile connector
  lmPathDigest <- hexDigestFile lmPath
  let
    topEntityDir = dropFileName lmPath
    boardPartTcl = mkBoardPartTcl boardPart
    globTcl
      | null globPatterns = "" :: String
      | otherwise =
          [__i|
        set extra_hdl_files [list]
        \# We use file join to be able to retrieve environment variables
        \# from our paths
        set glob_patterns "#{unlines $ fmap (\p -> "[file join " <> p <> "]") globPatterns}"
        foreach pat $glob_patterns {
          puts "Adding files matching $pat"
          set extra_hdl_files [concat $extra_hdl_files [glob $pat]]
        }
        add_files $extra_hdl_files
        |]

  execPrint_
    v
    [__i|
    \# #{lmPath}: #{lmPathDigest}
    \# #{connector}: #{connectorDigest}
    set_msg_config -severity {CRITICAL WARNING} -new_severity ERROR
    source -notrace {#{connector}}
    file delete -force {#{outputDir </> "ip"}}
    file mkdir {#{outputDir </> "ip"}}
    clash::readMetadata {#{topEntityDir}}

    set hasIp [expr [llength [clash::GetAllTclIfaces {purposes createIp}]] > 0]

    if {${hasIp}} {
      create_project -in_memory
      #{boardPartTcl}
      set ips [clash::createIp -dir {#{outputDir </> "ip"}}]
      set ipFiles [get_property IP_FILE [get_ips $ips]]
      close_project
    }

    clash::readHdl
    #{boardPartTcl}
    #{globTcl}
    if {${hasIp}} {
      read_ip $ipFiles
      set_property GENERATE_SYNTH_CHECKPOINT false [get_files $ipFiles]
      generate_target {synthesis simulation} [get_ips $ips]
    }

    clash::readXdc {early normal late}
    set_property TOP $clash::topEntity [current_fileset]
  |]

runSynthesis ::
  -- | Directory to write logs and checkpoints to
  FilePath ->
  -- | Out of context?
  Bool ->
  -- | Board part or part to synthesize for. E.g., 'xcku040-ffva1156-2-e'.
  BoardPart ->
  -- | List of filepaths to XDC files
  [FilePath] ->
  -- | List of glob patterns to external HDL files.
  [TclGlobPattern] ->
  -- | Manifests of which the first is the top-level to synthesize
  LocatedManifest ->
  {- | Path to tclConnector: a Tcl script that can parse Clash output and emit
  the correct commands for loading the design into Vivado
  -}
  FilePath ->
  IO ()
runSynthesis
  outputDir
  outOfContext
  boardPart
  constraints
  globPatterns
  manifest@LocatedManifest{lmManifest}
  connector = with $ \v -> do
    execBaseTcl v outputDir globPatterns manifest boardPart connector

    constraintDigests <- unlines <$> mapM constraintDigest constraints
    putStrLn constraintDigests

    execCmd_ v "set_msg_config" ["-severity {CRITICAL WARNING}", "-new_severity ERROR"]
    forM_ constraints (\xdcPath -> execCmd v "read_xdc" ["-unmanaged {" <> xdcPath <> "}"])

    -- Synthesis
    execCmd_
      v
      "synth_design"
      [ "-name " <> unpack (topComponent lmManifest)
      , "-mode " <> if outOfContext then "outOfContext" else "default"
      ]
    createDirectoryIfMissing True $ outputDir </> "reports"
    createDirectoryIfMissing True $ outputDir </> "checkpoints"
    execCmd_
      v
      "report_methodology"
      ["-file {" <> outputDir </> "reports" </> "post_synth_methodology.rpt}"]
    execCmd_
      v
      "report_timing_summary"
      ["-file {" <> outputDir </> "reports" </> "post_synth_timing_summary.rpt}"]
    execCmd_
      v
      "report_utilization"
      ["-file {" <> outputDir </> "reports" </> "post_synth_util.rpt}"]
    execCmd_
      v
      "write_checkpoint"
      ["-force", "{" <> outputDir </> "checkpoints" </> "post_synth.dcp}"]

    -- Netlist
    createDirectoryIfMissing True $ outputDir </> "netlist"
    execCmd_
      v
      "write_verilog"
      ["-force", outputDir </> "netlist" </> "netlist.v"]
    execCmd_
      v
      "write_xdc"
      ["-no_fixed_only", "-force", outputDir </> "netlist" </> "netlist.xdc"]
   where
    constraintDigest path = do
      pathDigest <- hexDigestFile path
      pure [__i|\# #{path}: #{pathDigest}|]

runPlaceAndRoute :: FilePath -> IO ()
runPlaceAndRoute outputDir = with $ \v ->
  execPrint_
    v
    [__i|
    set_msg_config -severity {CRITICAL WARNING} -new_severity ERROR

    \# Pick up where synthesis left off
    open_checkpoint {#{outputDir </> "checkpoints" </> "post_synth.dcp"}}

    \# Run optimization & placement
    opt_design
    place_design
    phys_opt_design
    write_checkpoint -force {#{outputDir </> "checkpoints" </> "post_place.dcp"}}

    \# Routing
    route_design
    write_checkpoint -force {#{outputDir </> "checkpoints" </> "post_route.dcp"}}
    report_methodology -file {#{outputDir </> "reports" </> "post_route_methodology.rpt"}}
    report_timing_summary -file {#{outputDir </> "reports" </> "post_route_timing_summary.rpt"}}
    report_timing -sort_by group -max_paths 100 -path_type summary -file {#{outputDir </> "reports" </> "post_route_timing.rpt"}}

    report_clock_utilization -file {#{outputDir </> "reports" </> "post_route_clock_util.rpt"}}
    report_utilization       -file {#{outputDir </> "reports" </> "post_route_util.rpt"}}
    report_power             -file {#{outputDir </> "reports" </> "post_route_power.rpt"}}
    report_drc               -file {#{outputDir </> "reports" </> "post_route_drc.rpt"}}

    \# Generate netlist and constraints
    file mkdir {#{outputDir </> "netlist"}}
    write_verilog -force {#{outputDir </> "netlist" </> "netlist.v"}}
    write_xdc -no_fixed_only -force {#{outputDir </> "netlist" </> "netlist.xdc"}}
|]

runBitstreamGen :: FilePath -> IO ()
runBitstreamGen outputDir = with $ \v -> do
  execCmd_ v "set_msg_config" ["-severity {CRITICAL WARNING}", "-new_severity ERROR"]

  -- Pick up where netlist left off
  execPrint_
    v
    ("open_checkpoint {" <> outputDir </> "checkpoints" </> "post_route.dcp" <> "}")

  -- Generate bitstream
  execPrint_ v "set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]"
  execPrint_ v ("write_bitstream -force {" <> outputDir </> "bitstream.bit" <> "}")

runProbesFileGen :: FilePath -> IO ()
runProbesFileGen outputDir = with $ \v -> do
  execPrint_ v "set_msg_config -severity {CRITICAL WARNING} -new_severity ERROR"

  -- Pick up where netlist left off
  execPrint_
    v
    ("open_checkpoint {" <> outputDir </> "checkpoints" </> "post_route.dcp" <> "}")

  -- Generate probes file
  execPrint_ v ("write_debug_probes -force {" <> outputDir </> "probes.ltx" <> "}")

{- | Programs the bitstream onto the given hardware targets using @openFPGALoader@.

Unlike a Vivado-based flow, each target is programmed by its own @openFPGALoader@
process talking to a single FTDI JTAG adapter. As every adapter is an independent
USB device, the uploads are run concurrently, which is a significant speedup over
programming the boards one at a time.

This only loads the bitstream into the FPGA's SRAM; it does not touch the VIO/ILA
debug probes (the @.ltx@ file). Those are still set up by Vivado in the HITL test
lifecycle ('runHitlTest'), which connects to the already-configured design.
-}
programBitstream ::
  (HasCallStack) =>
  -- | Directory where the bitstream files are located
  FilePath ->
  -- | The hardware targets to program
  [DeviceInfo] ->
  IO ()
programBitstream outputDir deviceInfos0 = do
  putStrLn "Starting programming of given hardware targets..."
  if null deviceInfos0
    then putStrLn "[WARNING] Not programming as no hardware targets were given."
    else do
      let
        bitstreamPath = outputDir </> "bitstream.bit"
        deviceInfos = nubOrd deviceInfos0
      results <- mapConcurrently (programDeviceWith bitstreamPath) deviceInfos
      let failures = [(d, err) | (d, Left err) <- zip deviceInfos results]
      unless (null failures) $
        error $
          "Failed to program "
            <> show (length failures)
            <> " out of "
            <> show (length deviceInfos)
            <> " hardware target(s) with openFPGALoader:\n"
            <> unlines ['\t' : d.deviceId <> ": " <> err | (d, err) <- failures]

{- | Program a single device with @openFPGALoader@. Returns 'Left' with a
human-readable error on failure, 'Right' on success.

The board's Digilent FT232H JTAG adapter is selected by its FTDI serial number, which
equals the 'deviceId'. Note this is a /different/ adapter from the FTDI FT2232C used by
OpenOCD for VexRiscv debugging (whose location is in 'usbAdapterLocation'); selecting
by serial avoids accidentally talking to the VexRiscv TAP.

The @digilent_hs2@ cable profile is required for these adapters, and @--index-chain 0@
selects the FPGA, which is the first of two devices on the JTAG chain.
-}
programDeviceWith :: FilePath -> DeviceInfo -> IO (Either String ())
programDeviceWith bitstreamPath deviceInfo = do
  putStrLn $ "Programming " <> deviceInfo.deviceId <> " with openFPGALoader..."
  let
    args =
      [ "--cable"
      , "digilent_hs2"
      , "--ftdi-serial"
      , deviceInfo.deviceId
      , "--index-chain"
      , "0"
      , "--write-sram"
      , bitstreamPath
      ]
  (exitCode, out, err) <- readProcessWithExitCode "openFPGALoader" args ""
  pure $ case exitCode of
    ExitSuccess -> Right ()
    ExitFailure code ->
      Left $
        "openFPGALoader exited with code "
          <> show code
          <> "\nstdout:\n"
          <> out
          <> "\nstderr:\n"
          <> err

runHitlTest ::
  -- | The HITL test group to execute
  HitlTestGroup ->
  -- | Hardware server URL
  String ->
  -- | Path to the generated probes file
  FilePath ->
  -- | Filepath the the ILA data dump directory
  FilePath ->
  IO ExitCode
runHitlTest HitlTestGroup{topEntity, testCases, driverProc} url probesFilePath ilaDataDir = do
  putStrLn $
    "Starting HITL test for FPGA design '"
      <> show topEntity
      <> "' with "
      <> show (length testCases)
      <> " test cases..."

  let testCaseNames = (.name) <$> testCases
  when (anySame testCaseNames) $
    error $
      "HITL test case names must be unique within their test. Offenders: "
        <> show (testCaseNames \\ nubOrd testCaseNames)

  testResults <- forM (zip [1 :: Int ..] testCases) $ \(nr, htc@HitlTestCase{}) -> do
    putStrLn $
      "Starting HITL test case "
        <> show nr
        <> " out of "
        <> show (length testCases)
        <> " named '"
        <> htc.name
        <> "'..."
    let requestedIds = map idFromHwTRef (Map.keys htc.parameters)
    when (anySame requestedIds) $
      error $
        "Multiple references to the same hardware target: "
          <> show (requestedIds \\ nubOrd requestedIds)

    -- Resolve the hardware targets statically; this no longer requires a live
    -- Vivado connection. Drivers that need Vivado (for the HITL VIO or ILAs) open
    -- a session themselves through the 'withVivado' escape hatch.
    let
      refs = Map.keys htc.parameters
      synthHwT ref = HwTarget (url <> "/xilinx_tcf/_/" <> idFromHwTRef ref)
      targets = [(synthHwT ref, deviceInfoFromHwTRef ref) | ref <- refs]
      parameterData =
        [ (synthHwT ref, BitVector.unsafeToNatural (pack param), bitSizeOf param)
        | (ref, param) <- Map.toList htc.parameters
        ]

      env =
        HitlDriverEnv
          { withVivado = withVivado
          , testName = htc.name
          , targets = targets
          , parameterData = parameterData
          , probesFilePath = probesFilePath
          , ilaDataDir = ilaDataDir
          }

    let
      catchException :: SomeException -> IO ExitCode
      catchException e = do
        putStrLn $ "Caught exception while running driver function: " <> displayException e
        return $ ExitFailure 3

    exitCode <- catch (driverProc env) catchException
    pure (htc.name, exitCode)

  let failedTestCaseNames = fst <$> filter ((/= ExitSuccess) . snd) testResults
  if null failedTestCaseNames
    then do
      putStrLn $ "All " <> show (length testCases) <> " HITL test cases passed."
    else do
      putStrLn $
        show (length failedTestCaseNames)
          <> " out of "
          <> show (length testCases)
          <> " HITL test cases failed or timed out, namely:"
      mapM_ (putStrLn . ('\t' :)) failedTestCaseNames
  pure $ maximum $ map snd testResults
 where
  -- \| Open a single Vivado session connected to the hardware server, run the
  -- given action in it, then close it. Drivers that need Vivado call this at most
  -- once, wrapping their entire Vivado-touching region. Vivado is slow to start,
  -- so calling it more than once per driver should be avoided.
  withVivado :: forall a. VivadoM a -> IO a
  withVivado action = do
    result <- try @TclException $ with $ \v -> do
      execCmd_ v "set_msg_config" ["-severity {CRITICAL WARNING}", "-new_severity ERROR"]
      execCmd_ v "open_hw_manager" []
      execCmd_ v "connect_hw_server" ["-url " <> url]
      runReaderT action v
    case result of
      Left e@TclException{} -> do
        print e
        throwIO e
      Right a -> pure a

{- | The 'BitSize' of a value as a 'Natural'. Lets us read the bit size of an
existentially-quantified ('BitPack') test parameter.
-}
bitSizeOf :: forall a. (BitPack a) => a -> Natural
bitSizeOf _ = natToNatural @(BitSize a)
