# SPDX-FileCopyrightText: 2022 Google LLC
#
# SPDX-License-Identifier: Apache-2.0

name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
 group: ${{ github.head_ref || github.run_id }}
 cancel-in-progress: true

jobs:
  license-check:
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
    steps:
    - uses: actions/checkout@v1
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1


  lint:
    name: Basic linting
    runs-on: self-hosted
    container:
      image: ubuntu:22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y pcregrep

      - name: EOL whitespace
        run: |
          .github/scripts/check_eol_whitespace.sh

      - name: Enforce EOF newline
        run: |
          .github/scripts/check_missing_eof_newline.sh

  build:
    name: Build dependencies
    runs-on: self-hosted

    container:
      image: ghcr.io/clash-lang/clash-ci-9.0.2:2022-02-02

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project.simulation cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: Build
        run: |
          cabal build all --only-dependencies

  elastic-buffer-sim-topologies:
    name: Simulate network
    runs-on: self-hosted
    needs: [build, lint]

    container:
      image: ghcr.io/clash-lang/clash-ci-9.0.2:2022-02-02

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project.simulation cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: Install poetry
        run: |
          apt-get update
          apt-get install python3-distutils -y
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          cd elastic-buffer-sim && poetry update

      - name: Lint Python script
        run: |
          cd elastic-buffer-sim && poetry run pycodestyle genplots.py

      # TODO: simulate + plot multiple topologies
      - name: Plot mesh grid
        run: |
          cabal build elastic-buffer-sim:sim
          cd elastic-buffer-sim && poetry run $(cabal list-bin elastic-buffer-sim:sim) +RTS -M8M -RTS plot complete3 150000 100

      - name: Upload plots
        uses: actions/upload-artifact@v2
        with:
          name: gen-plots-hs
          path: |
            elastic-buffer-sim/_build/clockscomplete3.pdf
            elastic-buffer-sim/_build/elasticbufferscomplete3.pdf

  elastic-buffer-sim-tests:
    name: elastic-buffer-sim unittests
    runs-on: self-hosted
    needs: [build, lint]

    container:
      image: ghcr.io/clash-lang/clash-ci-9.0.2:2022-02-02

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project.simulation cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: Run unittests
        run: |
          cabal run elastic-buffer-sim:unittests

  contranomy-tests:
    name: Contranomy tests
    runs-on: self-hosted
    needs: [build, lint]

    container:
      image: ghcr.io/clash-lang/clash-ci-9.0.2:2022-02-02

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project.simulation cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: Run unittests
        run: |
          cabal run contranomy:unittests

  contranomy-hdl:
    name: Generate Contranomy HDL
    runs-on: self-hosted
    needs: [build, lint]

    container:
      image: ghcr.io/clash-lang/clash-ci-9.0.2:2022-02-02

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project.formal cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: Build Contranomy
        run: |
          cd contranomy
          cabal run clash -- --version
          cat ../dist-newstyle/cache/plan.json | python3 -m json.tool | grep -C 1 riscv-altopts

      - name: Generate HDL
        run: |
          cd contranomy
          cabal run -- clash --verilog -main-is contranomyRVFITE Contranomy

      - name: Archive HDL
        run: |
          tar -c -f contranomy-hdl.tar contranomy/verilog

      - name: Upload Contranomy HDL
        uses: actions/upload-artifact@v2
        with:
          name: contranomy-hdl
          path: contranomy-hdl.tar

      - name: Get test matrix
        run: |
          if .github/scripts/has_riscv_changes.sh; then
            .github/scripts/get_formal_checks.sh
          else
            echo '["formal-checks-disabled"]' > checks.json
          fi

      - name: Set test matrix
        id: set-matrix
        run: |
          echo "check_matrix=$(cat checks.json)" >> "$GITHUB_OUTPUT"

    outputs:
      check_matrix: ${{ steps.set-matrix.outputs.check_matrix }}

  contranomy-formal-tests:
    name: RISC-V Formal checks
    needs: contranomy-hdl

    # We outsource these jobs to public runners, because the formal checks
    # trigger a massive number of jobs - many more than runners on our local
    # systems.
    #
    # Note: most of the time this shouldn't be triggered - only if contranomy
    #       or dependencies change.
    #
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/clash-lang/clash-ci-9.0.2:2022-02-02

    strategy:
      matrix:
        check: ${{ fromJson(needs.contranomy-hdl.outputs.check_matrix) }}
      fail-fast: false

    steps:
      - name: Checkout
        if: matrix.check != 'formal-checks-disabled'
        uses: actions/checkout@v1

      - name: Download Contranomy HDL
        if: matrix.check != 'formal-checks-disabled'
        uses: actions/download-artifact@v2
        with:
          name: contranomy-hdl

      - name: Extract HDL
        if: matrix.check != 'formal-checks-disabled'
        run: |
          tar -x -f contranomy-hdl.tar

      - name: Verify ${{ matrix.check }}
        if: matrix.check != 'formal-checks-disabled'
        run: |
          .github/scripts/run_riscv_formal_check.sh ${{ matrix.check }}

      - name: Verification failed, uploading results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: verify-${{ matrix.check }}-failed
          path: riscv-formal/cores/contranomy/checks/${{ matrix.check }}

  contranomy-sim-tests:
    name: ContranomySim tests and firmware integration tests
    runs-on: self-hosted
    needs: [build, lint, firmware-build-integration-tests]

    container:
      image: ghcr.io/clash-lang/clash-ci-9.0.2:2022-02-02

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project.simulation cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: Download Firmware Integration Tests
        uses: actions/download-artifact@v2
        with:
          name: firmware-integration-tests

      - name: Extract Firmware Integration Tests
        run: |
          tar -x -f firmware-integration-tests.tar

      - name: Run unittests
        run: |
          cabal run elastic-buffer-sim:unittests


  bittide-tests:
    name: Bittide tests
    runs-on: self-hosted
    needs: [build, lint]

    container:
      image: ghcr.io/clash-lang/clash-ci-9.0.2:2022-02-02

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project.simulation cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: Unittests
        run: |
          # While Hedgehog can fill many cores with "work", it doesn't actually
          # speed up the tests.
          cabal run -- bittide:unittests -j 1 +RTS -N2

  firmware-lints:
    name: Firmware Lints
    runs-on: self-hosted
    container:
      image: ubuntu:22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl build-essential

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt

      - name: Rust formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  firmware-unit-tests:
    name: Firmware Unit Tests
    runs-on: self-hosted
    container:
      image: ubuntu:22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl build-essential

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - uses: actions/cache@v3
        name: Cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-cache-${{ hashFiles('Cargo.lock') }}

      - name: Running Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

  firmware-build-examples:
    name: Firmware Build Examples
    runs-on: self-hosted
    container:
      image: ubuntu:22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl build-essential

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: riscv32imc-unknown-none-elf

      - uses: actions/cache@v3
        name: Cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            firmware/examples/hello/target/
          key: cargo-cache-${{ hashFiles('firmware/examples/hello/Cargo.lock') }}

      - name: Building "hello" Example
        run: cargo build --release
        working-directory: firmware/examples/hello

      - name: Building "fdt-read" Example
        run: cargo build --release
        working-directory: firmware/examples/hello

  firmware-build-integration-tests:
    name: Firmware Build Integration Tests
    runs-on: self-hosted
    container:
      image: ubuntu:22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl build-essential

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: riscv32imc-unknown-none-elf

      - uses: actions/cache@v3
        name: Cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            firmware/tests/target/
          key: cargo-cache-${{ hashFiles('firmware/tests/Cargo.lock') }}

      - name: Building Firmware Integration Tests
        run: cargo build --release
        working-directory: firmware/tests

      - name: Archive Firmware Integration Tests
        run: |
          mkdir -p target/firmware-integration-tests
          # Copy artefacts into "clean" folder
          cat target/artifacts | xargs -i cp ./{} target/firmware-integration-tests/
          cd target/; tar -c -f ../firmware-integration-tests.tar firmware-integration-tests/
        working-directory: firmware/tests/

      - name: Upload Firmware Integration Tests
        uses: actions/upload-artifact@v2
        with:
          name: firmware-integration-tests
          path: firmware/tests/firmware-integration-tests.tar

  bittide-instances-doctests:
    name: bittide-instances doctests
    runs-on: ubuntu-latest
    needs: [build, lint]

    container:
      image: ghcr.io/clash-lang/clash-ci-9.0.2:2022-02-02

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project.formal cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: Doctests
        run : |
          cabal run -- bittide-instances:doctests

  bittide-instances-unittests:
    name: bittide-instances unittests
    runs-on: ubuntu-latest
    needs: [build, lint]

    container:
      image: ghcr.io/clash-lang/clash-ci-9.0.2:2022-02-02

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project.formal cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: Unit tests
        run : |
          cabal run -- bittide-instances:unittests

  bittide-instances-hdl:
    name: bittide-instances synthesis
    runs-on: self-hosted
    env:
      SYNTHESIS_PART: xcku040-ffva1156-2-e
      # SYNTHESIS_PART: xcku035-ffva1156-2-e
    needs: [build, lint]

    strategy:
      matrix:
        target:
          - {top: switchCalendar1k,            stage: hdl}
          - {top: switchCalendar1kReducedPins, stage: netlist}

    container:
      image: ghcr.io/clash-lang/clash-ci-9.0.2:2022-02-02
      volumes:
        - /opt/tools:/opt/tools
      options: --mac-address="6c:5a:b0:6c:13:0b"

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          # We use the same flags as the 'build' step to reuse caches. This
          # "simulation" config only sets altopts on the Risc core, which we
          # don't synthesize yet.
          #
          # TODO: Either switch to VexRisc or update cache strategy.
          #
          cp .github/cabal.project.simulation cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: HDL generation and synthesis
        run : |
          .github/scripts/with_vivado.sh cabal run -- bittide-instances:shake ${{ matrix.target.top }}:${{ matrix.target.stage }}

      - name: Archive synthesis artifacts
        uses: actions/upload-artifact@v3
        with:
          name: _build
          path: _build
          retention-days: 14

  all:
    name: All jobs finished
    needs: [
        license-check,
        contranomy-formal-tests,
        contranomy-tests,
        contranomy-sim-tests,
        bittide-tests,
        firmware-lints,
        firmware-unit-tests,
        firmware-build-examples
      ]
    runs-on: self-hosted
    container:
      image: ubuntu:22.04
    steps:
      - name: Void
        run: |
          echo "All good"
