# SPDX-FileCopyrightText: 2022 Google LLC
#
# SPDX-License-Identifier: Apache-2.0

name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
 group: ${{ github.head_ref || github.run_id }}
 cancel-in-progress: true

jobs:
  lint:
    name: Basic linting
    runs-on: self-hosted
    container:
      image: ubuntu:22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          .github/scripts/set_de_mirror.sh
          apt-get update
          apt-get install -y pcregrep

      - name: EOL whitespace
        run: |
          .github/scripts/check_eol_whitespace.sh

      - name: Enforce EOF newline
        run: |
          .github/scripts/check_missing_eof_newline.sh

  build:
    name: Build dependencies
    runs-on: self-hosted

    container:
      image: ghcr.io/clash-lang/clash-ci-9.0.2:2022-12-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set CI flags
        run: |
          cp .github/cabal.project.simulation cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/store

          key: packages-cachebust-1-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-cachebust-1-

      - name: Build
        run: |
          cabal build all --only-dependencies

  bittide-instances-hdl:
    name: bittide-instances synthesis
    runs-on: self-hosted
    env:
      SYNTHESIS_PART: xcku040-ffva1156-2-e
      # SYNTHESIS_PART: xcku035-ffva1156-2-e
    needs: [build, lint]

    strategy:
      matrix:
        target:
          - {top: callisto3,                   stage: netlist}

    container:
      image: ghcr.io/clash-lang/clash-ci-9.0.2:2022-12-13
      volumes:
        - /opt/tools:/opt/tools
      options: --mac-address="6c:5a:b0:6c:13:0b"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set CI flags
        run: |
          # We use the same flags as the 'build' step to reuse caches. This
          # "simulation" config only sets altopts on the Risc core, which we
          # don't synthesize yet.
          #
          # TODO: Either switch to VexRisc or update cache strategy.
          #
          cp .github/cabal.project.simulation cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/store

          key: packages-cachebust-1-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-cachebust-1-

      - name: HDL generation and synthesis
        run : |
          .github/scripts/set_de_mirror.sh
          .github/scripts/with_vivado.sh cabal run -- bittide-instances:shake ${{ matrix.target.top }}:${{ matrix.target.stage }}

      - name: Archive synthesis artifacts
        uses: actions/upload-artifact@v3
        with:
          name: _build
          path: _build
          retention-days: 14
