name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
 group: ${{ github.head_ref || github.run_id }}
 cancel-in-progress: true

jobs:
  lint:
    name: Basic linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pcregrep

      - name: EOL whitespace
        run: |
          .github/scripts/check_eol_whitespace.sh

      - name: Enforce EOF newline
        run: |
          .github/scripts/check_missing_eof_newline.sh

  build:
    name: Build dependencies
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/clash-lang/clash-ci-8.10.2:2022-01-20

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: Build
        run: |
          cabal build all --only-dependencies

  contranomy-tests:
    name: Contranomy tests
    runs-on: ubuntu-latest
    needs: [build, lint]

    container:
      image: ghcr.io/clash-lang/clash-ci-8.10.2:2022-01-20

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: Run unittests
        run: |
          cabal run contranomy:unittests

  contranomy-hdl:
    name: Generate Contranomy HDL
    runs-on: ubuntu-latest
    needs: [build, lint]

    container:
      image: ghcr.io/clash-lang/clash-ci-8.10.2:2022-01-20

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: Build Contranomy
        run: |
          cd contranomy
          cabal run clash -- --version
          cat ../dist-newstyle/cache/plan.json | python3 -m json.tool | grep -C 1 riscv-altopts

      - name: Generate HDL
        run: |
          cd contranomy
          cabal run -- clash --verilog -main-is contranomyRVFITE Contranomy

      - name: Archive HDL
        run: |
          tar -c -f contranomy-hdl.tar contranomy/verilog

      - name: Upload Contranomy HDL
        uses: actions/upload-artifact@v2
        with:
          name: contranomy-hdl
          path: contranomy-hdl.tar

      - name: Get test matrix
        run: |
          .github/scripts/get_formal_checks.sh

      - name: Set test matrix
        id: set-matrix
        run: |
          echo "::set-output name=check_matrix::$(cat checks.json)"

    outputs:
      check_matrix: ${{ steps.set-matrix.outputs.check_matrix }}

  contranomy-formal-tests:
    name: RISC-V Formal checks
    needs: contranomy-hdl
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/clash-lang/clash-ci-8.10.2:2022-01-20

    strategy:
      matrix:
        check: ${{ fromJson(needs.contranomy-hdl.outputs.check_matrix) }}
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download Contranomy HDL
        uses: actions/download-artifact@v2
        with:
          name: contranomy-hdl

      - name: Extract HDL
        run: |
          tar -x -f contranomy-hdl.tar

      - name: Verify ${{ matrix.check }}
        run: |
          if .github/scripts/has_riscv_changes.sh; then
            .github/scripts/run_riscv_formal_check.sh ${{ matrix.check }}
          fi

      - name: Verification failed, uploading results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: verify-${{ matrix.check }}-failed
          path: riscv-formal/cores/contranomy/checks/${{ matrix.check }}

  bittide-tests:
    name: Bittide tests
    runs-on: ubuntu-latest
    needs: [build, lint]

    container:
      image: ghcr.io/clash-lang/clash-ci-8.10.2:2022-01-20

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: packages-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: packages-

      - name: Unittests
        run : |
          cabal run -- bittide:unittests

  firmware-lints:
    name: Firmware Lints
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt

      - name: Rust formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  firmware-unit-tests:
    name: Firmware Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Running Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

  firmware-build-examples:
    name: Firmware Build Examples
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: riscv32imc-unknown-none-elf

      - name: Building "hello" Example
        run: cargo build --release
        working-directory: firmware/examples/hello

  all:
    name: All jobs finished
    needs: [
        contranomy-formal-tests,
        contranomy-tests,
        bittide-tests,
        firmware-lints,
        firmware-unit-tests,
        firmware-build-examples
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Void
        run: |
          echo "All good"
