name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
 group: ${{ github.head_ref || github.run_id }}
 cancel-in-progress: true

jobs:
  lint:
    name: Basic linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pcregrep

      - name: EOL whitespace
        run: |
          .github/scripts/check_eol_whitespace.sh

      - name: Enforce EOF newline
        run: |
          .github/scripts/check_missing_eof_newline.sh

  build-contranomy:
    name: Build Contranomy using Clash and run unittests
    runs-on: ubuntu-latest
    needs: lint

    container:
      image: ghcr.io/clash-lang/clash-ci-8.10.2:2022-01-20

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set CI flags
        run: |
          cp .github/cabal.project cabal.project.local

      - name: Update Cabal index info
        run: |
          cabal update
          cabal freeze

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store

          key: contranomy-v2-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: contranomy-v2-

      - name: Build Contranomy
        run: |
          cd contranomy
          cabal run clash -- --version
          cat ../dist-newstyle/cache/plan.json | python3 -m json.tool | grep -C 1 riscv-altopts

      - name: Run unittests
        run: |
          cd contranomy
          cabal run unittests

      - name: Generate HDL
        run: |
          cd contranomy
          cabal run -- clash --verilog -main-is contranomyRVFITE Contranomy

      - name: Archive HDL
        run: |
          tar -c -f contranomy-hdl.tar contranomy/verilog

      - name: Upload Contranomy HDL
        uses: actions/upload-artifact@v2
        with:
          name: contranomy-hdl
          path: contranomy-hdl.tar

      - name: Get test matrix
        run: |
          .github/scripts/get_formal_checks.sh

      - name: Set test matrix
        id: set-matrix
        run: |
          echo "::set-output name=check_matrix::$(cat checks.json)"

    outputs:
      check_matrix: ${{ steps.set-matrix.outputs.check_matrix }}

  verify-contranomy:
    name: RISC-V Formal checks
    needs: build-contranomy
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/clash-lang/clash-ci-8.10.2:2022-01-20

    strategy:
      matrix:
        check: ${{ fromJson(needs.build-contranomy.outputs.check_matrix) }}
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download Contranomy HDL
        uses: actions/download-artifact@v2
        with:
          name: contranomy-hdl

      - name: Extract HDL
        run: |
          tar -x -f contranomy-hdl.tar

      - name: Verify ${{ matrix.check }}
        run: |
          .github/scripts/run_riscv_formal_check.sh ${{ matrix.check }}

      - name: Verification failed, uploading results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: verify-${{ matrix.check }}-failed
          path: riscv-formal/cores/contranomy/checks/${{ matrix.check }}

  all:
    name: All jobs finished
    needs: verify-contranomy
    runs-on: ubuntu-latest
    steps:
      - name: Void
        run: |
          echo "All good"
