# SPDX-FileCopyrightText: 2025 Google LLC
#
# SPDX-License-Identifier: Apache-2.0

name: 'Check Pull Request labels for merge block'

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  do-not-merge:
    if: contains(github.event.pull_request.labels.*.name, 'do-not-merge')
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: exit 1
